-- Schema matching the original SQLAlchemy models exactly, so the Java
-- backend is a drop-in replacement for the Python backend:
--
-- users:      id, username, email, hashed_password, created_at
-- contacts:   id, name, phone_number, email, address, created_at
--
-- Uses standard SQL (identity columns, TIMESTAMP WITH TIME ZONE) so the
-- same script also runs on the H2 database used by the test suite.

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);
CREATE INDEX idx_users_username ON users (username);

CREATE TABLE contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_contacts_phone UNIQUE (phone_number),
    CONSTRAINT uk_contacts_email UNIQUE (email)
);
CREATE INDEX idx_contacts_phone_number ON contacts (phone_number);
